### ISSUE TITLE
Замечания @savvbuck лаб2

### ISSUE THREAD

**Issue by ananasn** [ITMOPython-2023/lab2#1]
@savvbuck

* Зачем использовать префикс u при определении строкового литерала? Напишите, почему можно обойтись без него в Python3
*  Вместо конкатенации строк используйте f-строки (ВЕЗДЕ)
*  Повторяющийся код (меняется только параметр row2_l). Сделайте функцию с параметром для  рисования  строки.
```python
    #creates second row of the red circle
    sys.stdout.write(f'\u001b[1A')
    sys.stdout.write(f'\u001b[' + str(row2_l - step_bw_rows) + 'D')
    sys.stdout.write(f'\u001b[41;1m ' * row2_l)

    #creates third row of the red circle
    sys.stdout.write(f'\u001b[1A')
    sys.stdout.write(f'\u001b[' + str(row3_l - step_bw_rows) + 'D')
    sys.stdout.write(f'\u001b[41;1m ' * row3_l)

    #creates fourth row of the red circle
    sys.stdout.write(f'\u001b[1A')
    sys.stdout.write(f'\u001b[' + str(row2_l + step_bw_rows) + 'D')
    sys.stdout.write(f'\u001b[41;1m ' * row2_l)

    #creates fifth row of the red circle
    sys.stdout.write(f'\u001b[1A')
    sys.stdout.write(f'\u001b[' + str(row1_l + step_bw_rows) + 'D')
    sys.stdout.write(f'\u001b[41;1m ' * row1_l)
```

* Константы создаются обычно в глобальной области видимости и пишутся капсом по PEP8.
```python
    WIDTH = 11
    LENGTH = 24

    def pattern():
        ...

**Comment by savvbuck** [comment]
Поправил, то что вы сказали. Префикс u использовался в более ранних версиях питона(с 2.0 по 3.0) для того, чтобы указать тип строки - Unicode. В версии питона 3.0 строки по умолчанию использовать тип Unicode для строк, и такой префикс стал не валидным, а после его снова добавили с версии 3.2, чтобы сделать код, написанный на 2.0 совместимым с современной версией питона.
